### ISSUE TITLE
Some issues when running Kproximate (with pw authentication)

### ISSUE THREAD

**Issue by devedse** [lupinelab/kproximate#2]
Hello, I'd like to run kproximate with password authentication and using the root account on my proxmox node.

I've deployed it to my Proxmox cluster with the following configuration:
```
kproximate:
  config:
    kpNodeCores: 2
    kpNodeMemory: 2048
    kpNodeNamePrefix: k3s-autonode
    kpNodeTemplateName: cloudimage-UbuntuJammy-k3s-node-10110
    loadHeadroom: 0.2
    maxKpNodes: 4
    pmUrl: https://10.88.20.10:8006/api2/json
    pmUserID: root@pam

  secrets:
    pmToken: blahblah123 <-- password for proxmox
    rabbitmqPassword: superrabbitpw123
    sshKey: blahblah123 <-- password for root @ proxmox node
```

However when I deploy it nothing seems to happen. The pods have no logging and also don't seem to work.

**Comment by lupinelab** [comment]
Hi, password auth was not supported in 0.1.0. I've just released version 0.1.1 with support for this.

I'm surprised you aren't getting logs, I've replicated and I see the pods logging the failed auth attempts. In the future try grabbing all the logs for all pods with a label: `kubectl logs -n kproximate -l app.kubernetes.io/instance=kproximate -f`.

Also note that the `sshKey` secret value you are providing is ineffective, either do not supply it or pass your public ssh key. This feature uses cloudinit to setup ssh access to nodes created by kproximate.

Please update your config as suggested below:
```
kproximate:
  config:
    kpNodeCores: 2
    kpNodeMemory: 2048
    kpNodeNamePrefix: k3s-autonode
    kpNodeTemplateName: cloudimage-UbuntuJammy-k3s-node-10110
    loadHeadroom: 0.2
    maxKpNodes: 4
    pmUrl: https://10.88.20.10:8006/api2/json
    pmUserID: root@pam

  secrets:
    pmPassword: blahblah123 <-- password for proxmox
    rabbitmqPassword: superrabbitpw123
    sshKey: ssh-rsa blahblah <-- your public ssh key
```

Let me know if you are still having problems.
